//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beauty_Care.goods
{
    using System;
    using System.Collections.Generic;
    
    public partial class beautyGoods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beautyGoods()
        {
            this.cart = new HashSet<cart>();
            this.ordersManager = new HashSet<ordersManager>();
        }
    
        public int idGoods { get; set; }
        public string article { get; set; }
        public string nameGoods { get; set; }
        public int category { get; set; }
        public int typeGoods { get; set; }
        public int instock { get; set; }
        public decimal price { get; set; }
        public int manufacturer { get; set; }
        public string compound { get; set; }
        public string description { get; set; }
        public string image { get; set; }

        public string CurrentPhoto
        {
            get
            {
                if (string.IsNullOrEmpty(image) || String.IsNullOrWhiteSpace(image))
                {
                    return "/img/picture.png";
                }
                else
                {
                    return "/img/" + image;
                }
            }
        }

        public virtual category category1 { get; set; }
        public virtual manufacturer manufacturer1 { get; set; }
        public virtual typeGoods typeGoods1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordersManager> ordersManager { get; set; }
    }
}
